import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Nav } from "@/components/Nav";
import Script from "next/script";

export const graffitiYouth = localFont({
  src: "./fonts/GraffitiYouth-Regular.otf",
  variable: "--font-graffiti-youth",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className="antialiased">
        <Nav />
        {children}
        <Script
          src="https://kit.fontawesome.com/debda86926.js"
          crossOrigin="anonymous"
        />
      </body>
    </html>
  );
}
